version: "3.8"

services:
  directus:
    image: directus/directus:latest
    ports:
      - "${DIRECTUS_PORT:-8055}:8055"
    volumes:
      - directus_uploads:/directus/uploads
      - directus_extensions:/directus/extensions
    environment:
      SECRET: "${DIRECTUS_SECRET:-replace-with-secure-random-value}"
      DB_CLIENT: "pg"
      DB_HOST: "postgres"
      DB_PORT: "5432"
      DB_DATABASE: "${DB_NAME:-directus}"
      DB_USER: "${DB_USER:-directus}"
      DB_PASSWORD: "${DB_PASSWORD:-directus}"
      ADMIN_EMAIL: "${DIRECTUS_ADMIN_EMAIL:-admin@example.com}"
      ADMIN_PASSWORD: "${DIRECTUS_ADMIN_PASSWORD:-admin123}"
      CACHE_ENABLED: "false"
      RATE_LIMITER_ENABLED: "false"
      RATE_LIMITER_STORE: "memory"
      RATE_LIMITER_POINTS: "25"
      RATE_LIMITER_DURATION: "1"
      ACCESS_TOKEN_TTL: "15m"
      REFRESH_TOKEN_TTL: "7d"
      REFRESH_TOKEN_COOKIE_SECURE: "false"
      REFRESH_TOKEN_COOKIE_SAME_SITE: "lax"
      REFRESH_TOKEN_COOKIE_NAME: "directus_refresh_token"
      CORS_ENABLED: "true"
      CORS_ORIGIN: "${CORS_ORIGIN:-http://localhost:3000}"
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped

  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: "${DB_USER:-directus}"
      POSTGRES_PASSWORD: "${DB_PASSWORD:-directus}"
      POSTGRES_DB: "${DB_NAME:-directus}"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U ${DB_USER:-directus} -d ${DB_NAME:-directus}",
        ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    restart: unless-stopped

volumes:
  directus_uploads:
  directus_extensions:
  postgres_data:
